### ISSUE TITLE
Evaluate remove hack of posix wrapper

### ISSUE THREAD

**Issue by aldenml** [aldenml/libtorrent4j#14]
I'm thinking of removing this feature, it's a very fragile hack to fake a posix layer using the Android Storage Access Framework (SAF).

@proninyaroslav do you have any opinion on this?

**Comment by proninyaroslav** [comment]
Yes, it’s hard to get SAF working using native libraries. The main difficulty I encountered using `posix_wrapper` is that it still uses the classic file system path, which makes it almost impossible to use SD cards and other external storage devices, which are usually only Uri from content providers and get physical location or it's very difficult or impossible. And this problem makes `posix_wrapper` little useful. The solution to this situation would be to use `FileOutputStream` or `FileDescriptor`, but since this is a posix, this seems like a fantastic idea.

**Comment by aldenml** [comment]
Your experience is similar to the one I have. I will remove it then. I can always bring it back if in need of it.

**Comment by aldenml** [comment]
Done with https://github.com/aldenml/libtorrent4j/pull/15
